

  0%|                                                 | 0/13671 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "/hpi/fs00/home/jim.maar/miniconda3/envs/arena-env/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpi/fs00/home/jim.maar/miniconda3/envs/arena-env/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/hpi/fs00/home/jim.maar/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/hpi/fs00/home/jim.maar/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/hpi/fs00/home/jim.maar/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/hpi/fs00/home/jim.maar/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpi/fs00/home/jim.maar/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/hpi/fs00/home/jim.maar/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/hpi/fs00/home/jim.maar/interpretability/training_probes.py", line 303, in <module>
    trainer.train()
  File "/hpi/fs00/home/jim.maar/interpretability/training_probes.py", line 248, in train
    loss = trainer.training_step(indices)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpi/fs00/home/jim.maar/interpretability/training_probes.py", line 165, in training_step
    state_stack_one_hot = args.get_state_stack_one_hot(games_str).to(device)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpi/fs00/home/jim.maar/interpretability/training_utils.py", line 280, in get_state_stack_one_hot_first_tile_places_mine_theirs
    state_stack_first_tile_places_mine_theirs = get_state_stack_first_tile_places_mine_theirs(games_str)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpi/fs00/home/jim.maar/interpretability/training_utils.py", line 273, in get_state_stack_first_tile_places_mine_theirs
    state_stack_first_tile_places_mine_theirs = get_state_stack_first_tile_places_black_white(games_str)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpi/fs00/home/jim.maar/interpretability/training_utils.py", line 252, in get_state_stack_first_tile_places_black_white
    state_stack = seq_to_state_stack_flipped(games_str)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpi/fs00/home/jim.maar/interpretability/training_utils.py", line 133, in seq_to_state_stack_flipped
    flipped = board.umpire_return_flipped(move)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpi/fs00/home/jim.maar/interpretability/othello_world/mechanistic_interpretability/mech_interp_othello_utils.py", line 234, in umpire_return_flipped
    r, c = move // 8, move % 8
           ~~~~~^^~~
TypeError: unsupported operand type(s) for //: 'list' and 'int'